authors:
  tschinz:
    name: tschinz
    description: Creator of Z-Notes
    avatar: https://avatars.githubusercontent.com/u/1192968
    slug: tschinz       # Author profile slug
    url: https://github.com/tschinz