# Project information
site_name: Z-Notes
site_url: https://github.com/tschinz/znotes
site_author: tschinz
site_description: >-
  Personal Knowledge Base, for everything I want to remember.

# Repository
repo_name: tschinz/znotes
repo_url: https://github.com/tschinz/znotes

# Copyright
copyright: >
  Copyright &copy; 2004 - 2024 tschinz –
  <a href="#__consent">Change cookie settings</a>

# Configuration
theme:
  name: material
  logo: img/logo-light.svg
  icon:
    logo: logo
  favicon: img/favicon.png
  font:
    text: Fira Sans
    code: Fira Code
  palette:
    # colors red pink purple deep purple indigo blue light blue cyan teal green light green lime yellow amber orange deep orange brown grey blue grey black white
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: en
  features:
    - navigation.tabs     # enable tabs top section
    - navigation.sections # enable section on the left side
    - navigation.path     # show path navigation
    - navigation.indexes  # toplevel index is the first page
    - navigation.top      # back to top
    - navigation.tracking # url is updated with the current header
    #- navigation.footer   # footer navigation
    - toc.follow          # toc will follow you while scrolling
    - search.suggest      # search suggestions
    - search.highlight    # search term highlighting
    - search.share        # share button
    - announce.dismiss    # possibility to dismiss announcements
    - header.autohide     # autohide header on scroll
    - content.code.copy   # copy button for code blocks
extra:
  #alternate:
  #  - name: English
  #    link: /en/
  #    lang: en
  #  - name: Deutsch
  #    link: /de/
  #    lang: de
  homepage: https://tschinz.github.io/znotes/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/tschinz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/silvan-zahno-77160227/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.hevs.ch/silvan.zahno
    - icon: fontawesome/brands/github
      link: https://github.com/tschinz
  generator: false
plugins:
  #- meta
  - tags:
      tags_file: about/tags.md
  - search
  - blog:
      blog_toc: true
      authors_file: "{blog}/.authors.yml"
  - rss:
      enabled: !ENV [CI, false]
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - glightbox
markdown_extensions:
  - admonition                 # admonition boxes
  - attr_list                  # buttons, annotations, grids, etc.
  - md_in_html                 # grids
  - footnotes                  # footnotes
  - tables                     # datatables
  - pymdownx.details
  - pymdownx.critic            # formatting
  - pymdownx.caret             # formatting
  - pymdownx.keys              # formatting
  - pymdownx.mark              # formatting
  - pymdownx.tilde             # formatting
  - pymdownx.superfences
  - pymdownx.inlinehilite      # inline code blocks
  - pymdownx.snippets          # code blocks, tooltips
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:      # mermaid diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:            # emoji shortcodes
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list                   # definition lists
  - pymdownx.tasklist:         # task lists
      custom_checkbox: true
  - pymdownx.arithmatex:       # mathjax
      generic: true
  - abbr                       # tooltips

extra_javascript:
  - javascripts/mathjax.js    # mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # polyfill for mathjax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # mathjax

nav:
  - Home: index.md
  - About:
      - about/index.md
      - Getting started: about/getting_started.md
      - Hack this site: about/howtodocument.md
      - Credits: about/credits.md
  - Blog: blog/index.md